### ISSUE TITLE
execution issue

### ISSUE THREAD

**Issue by datalakeoff** [Azure-Samples/active-directory-node-webapi-basic#4]
PS C:\Users\abenayed\Documents\test\active-directory-node-webapi-basic> npm install

> dtrace-provider@0.8.7 install C:\Users\abenayed\Documents\test\active-directory-node-webapi-basic\node_modules\dtrace-provider
> node-gyp rebuild || node suppress-error.js

C:\Users\abenayed\Documents\test\active-directory-node-webapi-basic\node_modules\dtrace-provider>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Python37\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:294:12)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:970:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\abenayed\Documents\test\active-directory-node-webapi-basic\node_modules\dtrace-provider
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN active-directory-webapi-nodejs@0.0.1 No repository field.
npm WARN active-directory-webapi-nodejs@0.0.1 No license field.

added 135 packages from 230 contributors and audited 264 packages in 12.354s
found 0 vulnerabilities

**Comment by jmprieur** [comment]
Closing this issue as this sample is being archived
